feat(company role): support optional agreements
eclipse-tractusx/portal-frontend-registration pull request #173
Opened 2024-05-20 18:39 UTC by lavanya-bmw

## Description

Support optional agreements for company role

## Why

To support optional agreements with validation

## Issue

https://github.com/eclipse-tractusx/portal-frontend-registration/issues/130

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-05-21 05:28 UTC, nidhigarg-bmw approved these changes
lgtm

2024-05-21 07:23 UTC, oyo requested changes
guess that console.log was forgotten

2024-05-21 07:23 UTC, oyo commented on src/components/cax-companyRole.tsx
> +          console.log('errors', errors)
please remove console log

2024-05-21 07:30 UTC, lavanya-bmw commented on src/components/cax-companyRole.tsx
> +          console.log('errors', errors)
Removed console

2024-05-21 14:11 UTC, oyo submitted a review, later dismissed

2024-05-22 07:38 UTC, evegufy approved these changes

2024-05-22 07:39 UTC, merged