fix: remove logic that sets bpn before validation
eclipse-tractusx/portal-frontend-registration pull request #253
Opened 2024-09-13 08:30 UTC by JordanGerada3

## Description

- Removed prop from input field that was setting the BPNL on the from without being firstly validated

## Why

When a user would insert an invalid BPNL in the autofill field, the BPNL was updating in the form despite being invalid, leading to the possibility of the user submitting the application with an incorrect BPNL. 

## Issue

#252 

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

2024-09-13 08:50 UTC, typecastcloud approved these changes
Looks good.

2024-09-13 08:59 UTC, JordanGerada3 commented
> Looks good. Unintended behavior by the copy paste mess I made when adding onBlur logic. Thanks for the find!
> 
> Please update DEPENDENCIES file. See artifact here: https://github.com/eclipse-tractusx/portal-frontend-registration/actions/runs/10845856689

DEPENDENCIES updated!

2024-09-13 09:40 UTC, shubhamv-ss approved these changes
lgtm

2024-10-09 14:44 UTC, evegufy commented on CHANGELOG.md
> +- remove logic that sets bpn before validation [#253](https://github.com/eclipse-tractusx/portal-frontend-registration/pull/253)
please move to unreleased section

2024-10-09 14:50 UTC, JordanGerada3 commented on CHANGELOG.md
> +- remove logic that sets bpn before validation [#253](https://github.com/eclipse-tractusx/portal-frontend-registration/pull/253)
@evegufy I've resolved this now.

2024-10-09 15:23 UTC, evegufy approved these changes
lgtm, thank you @JordanGerada3

2024-10-09 15:25 UTC, evegufy requested changes
sorry, didn't see it earlier, could you please still update the DEPENDENCIES file again?

2024-10-11 08:07 UTC, JordanGerada3 commented
> sorry, didn't see it earlier, could you please still update the DEPENDENCIES file again?

@evegufy it seems that the failure happened before the artefact generation, therefore I have nothing to update the dependencies with. I also haven't introduced any new dependencies in my PR. Do you know how to solve this?

2024-10-21 07:17 UTC, evegufy commented
@JordanGerada3 sorry for the wait. We'll update the dependencies with another PR as this change doesn't include update to dependencies.

2024-10-21 07:18 UTC, evegufy approved these changes

2024-10-21 07:18 UTC, merged